package de.oio.tmj.addressbook.server.service;
//package de.oio.tmj.addressbook.shared.model;
//
//import java.util.ArrayList;
//import java.util.List;
//
//public class AddressMock {
//	private static int lastId;//TODO workaround until id is generated by DB.
//	
//	public static int getNewId() {
//		return ++lastId;
//	}
//	
////	public static List<Person> createPersons(){
////		Address address=new Address("Meierstraße 7, 22987 Hamburg, Germany");
////		Address.setPartSeparator(" * ");
////		System.out.println("separator="+getPartSeparator());
////		System.out.println("parts="+address.getParts());
////		System.out.println("address="+address);
////		System.out.println("address.asString="+address.asString());
////		System.out.println("parts="+address.getParts());
////		System.out.println("address="+address);
////		System.out.println("address.asString="+address.asString());
////		System.out.println();
////		address=new Address("Müllerweg 12","bei Meier");
////		address.addPart("München");
////		System.out.println("parts="+address.getParts());
////		System.out.println("address="+address);
////		System.out.println("parts="+address.getParts());
////		System.out.println("address="+address);
////		
////		return persons;
////	}
//}
