package de.oio.tmj.addressbook.server.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import de.oio.tmj.addressbook.shared.model.Mail;

@Component
public class MailMock {
//	private static int lastId;//TODO workaround until id is generated by DB.
//	@Autowired
//	private IdGenerator generator;
	
//	public static void main(String[] args) {
//		Mail mail=new Mail(()->generator.getNewId(),"hallo@faa.boo");
//		System.out.println("mail="+mail);
//		mail=new Mail("test","hallo@faa.boo");
//		System.out.println("mail="+mail);
//	}

//	public static int getNewId() {
//		return ++lastId;
//	}
	
}
