//package de.oio.tmj.addressbook.server.service;
//
//public class PhoneMock {
//	private static int lastId;//TODO workaround until id is generated by DB.
//	
//	public static int getNewId() {
//		return ++lastId;
//	}
//	
//}
//  