package de.oio.tmj.addressbook.server.dao;

import de.oio.tmj.addressbook.shared.model.Person;

public class PersonDAO {
	private static int lastId;//TODO workaround until id is generated by DB.
	
	public static int getNewId() {
		return ++lastId;
	}
	

//	public static void register(Person person) {
//		if(0==person.getId()) {
//			person.setId(++lastId);
//		}
//	}

}
